# Generated by Django 3.2.10 on 2022-03-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='full_name',
        ),
    ]
